/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  History: () => import('#controllers/history_controller'),
  News: () => import('#controllers/news_controller'),
  PoliticianTrades: () => import('#controllers/politician_trades_controller'),
  Portfolio: () => import('#controllers/portfolio_controller'),
  Symbol: () => import('#controllers/symbol_controller'),
}
