/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class NewsArticleSchema extends BaseModel {
  static $columns = ['ai', 'createdAt', 'description', 'externalId', 'headline', 'id', 'provider', 'publishedAt', 'relevanceRaw', 'sentimentScore', 'sourceName', 'storyId', 'summary', 'tickers', 'url'] as const
  $columns = NewsArticleSchema.$columns
  @column()
  declare ai: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column()
  declare externalId: string
  @column()
  declare headline: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare provider: string
  @column.dateTime()
  declare publishedAt: DateTime
  @column()
  declare relevanceRaw: number
  @column()
  declare sentimentScore: number
  @column()
  declare sourceName: string
  @column()
  declare storyId: number | null
  @column()
  declare summary: string
  @column()
  declare tickers: string
  @column()
  declare url: string
}

export class PortfolioSnapshotSchema extends BaseModel {
  static $columns = ['backfilled', 'cash', 'createdAt', 'id', 'totalValue'] as const
  $columns = PortfolioSnapshotSchema.$columns
  @column()
  declare backfilled: boolean
  @column()
  declare cash: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare totalValue: number
}

export class PositionSnapshotSchema extends BaseModel {
  static $columns = ['assetType', 'avgCost', 'createdAt', 'id', 'portfolioSnapshotId', 'price', 'quantity', 'symbol', 'value'] as const
  $columns = PositionSnapshotSchema.$columns
  @column()
  declare assetType: string
  @column()
  declare avgCost: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare portfolioSnapshotId: number
  @column()
  declare price: number
  @column()
  declare quantity: number
  @column()
  declare symbol: string
  @column()
  declare value: number
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
